import { z } from "zod";

export const PATIENT_STATUSES = ["Admitted", "Outpatient", "Discharged", "Critical"] as const;
export const GENDERS = ["M", "F"] as const;

export const patientStatus = z.enum(PATIENT_STATUSES);
export type PatientStatus = z.infer<typeof patientStatus>;

export const patientSchema = z.object({
  id: z.string(),
  name: z.string(),
  mrn: z.string(),
  age: z.number(),
  gender: z.enum(GENDERS),
  condition: z.string(),
  doctor: z.string(),
  status: patientStatus,
  lastVisit: z.string(),
});
export type Patient = z.infer<typeof patientSchema>;

/**
 * Payload submitted from the Add Patient form. `mrn` and `lastVisit` are
 * generated by the API on create, so they're omitted here.
 */
export const createPatientSchema = z.object({
  name: z.string().min(1, "Name is required"),
  age: z
    .number({ invalid_type_error: "Age is required" })
    .int("Age must be a whole number")
    .min(0, "Enter a valid age")
    .max(120, "Enter a valid age"),
  gender: z.enum(GENDERS),
  condition: z.string().min(1, "Condition is required"),
  doctor: z.string().min(1, "Assign a doctor"),
  status: patientStatus,
});
export type CreatePatientInput = z.infer<typeof createPatientSchema>;
